s = input()
ans = set()
ans.add(s[0] + s[1] + s[2])
ans.add(s[0] + s[2] + s[1])
ans.add(s[1] + s[0] + s[2])
ans.add(s[1] + s[2] + s[0])
ans.add(s[2] + s[0] + s[1])
ans.add(s[2] + s[1] + s[0])
print(len(ans))